spring:
#  mvc:
#    view:
#      prefix:
#      suffix: .html
  thymeleaf:
    encoding: UTF-8
    mode: HTML5
    servlet:
      content-type: text/html
    #缓存设置为false, 这样修改之后马上生效，便于调试
    cache: false

  datasource:
    name: mysql_test
    url: jdbc:mysql://localhost:3306/notarygroup?nullCatalogMeansCurrent=true&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=GMT%2B8&useSSL=true
    username: root
    password: lgh942020
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    #druid相关配置
    druid:

      filters: config,stat
      driver-class-name: com.mysql.cj.jdbc.Driver
      #基本属性
      url: jdbc:mysql://localhost:3306/notarygroup?nullCatalogMeansCurrent=true&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=GMT%2B8&useSSL=true
      username: root
      password: lgh942020
      #配置初始化大小/最小/最大
      initialSize: 1
      minIdle: 1
      maxActive: 500
      #获取连接等待超时时间
      maxWait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      timeBetweenEvictionRunsMillis: 60000
      #一个连接在池中最小生存的时间
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 500
      maxOpenPreparedStatements: 500

      connectionProperties: druid.stat.slowSqlMillis=200;druid.stat.logSlowSql=true;config.decrypt=true
      filter:
        wall:
          config:
            multi-statement-allow: true
  redis:
    database: 0
    host: localhost
    port: 6379
    password: cqupt
    timeout: 1000

## 该配置节点为独立的节点，如果将这个配置放在spring的节点下，会导致配置无法被识别
mybatis:
  #注意：一定要对应mapper映射xml文件的所在路径
  mapper-locations: classpath:mapping/*.xml
  # 注意：对应实体类的路径//entity扫描的包名
  type-aliases-package: com.unnet.hzfc.webconsole.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


#是否开启swagger
swagger:
  is:
    active: true

## 该配置节点为独立的节点，如果将这个配置放在spring的节点下，会导致配置无法被识别
mybatis-plus:
  #注意：一定要对应mapper映射xml文件的所在路径
  mapper-locations: classpath:mapping/*.xml
  # 注意：对应实体类的路径//entity扫描的包名
  type-aliases-package: com.unnet.hzfc.webconsole.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
  global-config:
    banner: false

